### ISSUE TITLE
deployed vercel doesn't shows anything after signing

### ISSUE THREAD

**Issue by star-gazer111** [kituuu/personal-space#1]
I tried using the vercel link & after signing in it just shows me this on the screen, even after multiple reloads :
[
![Screenshot from 2024-06-17 04-26-52](https://github.com/kituuu/personal-space/assets/117103753/7bde7534-2880-47d1-ae37-3d91d6e5d287)
](url)

Is the backend having some issue of not being connected?

Anyways, I just came across your project & opened it as it seemed a really nice one to go through & try!

**Comment by kituuu** [comment]
The button on the top right (just before the profile image) is used to upload photos to your gallery. I just created this project to understand the new features of next.js and make a prod-ready app. So, I have turned off the upload feature for other people because I'm using a fixed storage space service. If I make it public, people may upload anything in it.

**Comment by star-gazer111** [comment]
Ah okay, great job. Thanks!
